---
- name: install php apache module
  apt:
    update_cache: yes
    pkg:
      - php-fpm
      - php-apcu
  notify:
    - restart php-fpm

- name: install php extensions/modules
  apt:
    update_cache: yes
    pkg:
      - php-pear
      - php-gd
      - php-mysql
      - php-tideways
      - php-mbstring
      - php-intl
  notify:
    - restart php-fpm

- name: install pear Text_CAPTCHA module
  pear:
    name: Text_CAPTCHA
  notify:
    - restart php-fpm

# we have to say '-beta' or it won't install
# https://stackoverflow.com/questions/6780536/failed-to-download-pear-http-request2-within-preferred-state-stable
- name: install pear Image_Text module
  pear:
    name: Image_Text-beta
  notify:
    - restart php-fpm

- name: php tmp dir
  file:
    dest: /var/lib/php/tmp
    owner: www-data
    group: root
    state: directory
    mode: 0700

- name: php tmp upload dir
  file:
    dest: /var/lib/php/tmp_upload
    owner: www-data
    group: root
    state: directory
    mode: 0700

- name: php wsdl soap cache dir
  file:
    dest: /var/lib/php/soap_cache
    owner: www-data
    group: root
    state: directory
    mode: 0700

- name: enable apache proxy (depend)
  file:
    src: /etc/apache2/mods-available/proxy.load
    dest: /etc/apache2/mods-enabled/proxy.load
    state: link
  notify:
    - restart php-fpm
    - restart apache

- name: enable apache proxy_fcgi (depend)
  file:
    src: /etc/apache2/mods-available/proxy_fcgi.load
    dest: /etc/apache2/mods-enabled/proxy_fcgi.load
    state: link
  notify:
    - restart php-fpm
    - restart apache

- name: enable apache php-fpm
  file:
    src: /etc/apache2/conf-available/php8.2-fpm.conf
    dest: /etc/apache2/conf-enabled/php8.2-fpm.conf
    state: link
  notify:
    - restart php-fpm
    - restart apache

- name: configure php.ini
  template:
    src: php_8.2.ini.j2
    dest: /etc/php/8.2/fpm/php.ini
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify:
    - restart php-fpm
