- name: phplist cron
  template:
    src: phplist_cron.j2
    dest: /etc/cron.d/phplist_cron
    owner: root
    group: root
    mode: 0644

- name: Create log dir for phplist cron
  file:
    dest: /var/log/phplist
    owner: www-data
    group: www-data
    state: directory
    mode: 0750

- name: xhprof cron
  template:
    src: xhprof_cron.j2
    dest: /etc/cron.d/xhprof_cron
    owner: root
    group: root
    mode: 0644

