---
- name: install awstats and plugin depends
  apt:
    update_cache: yes
    pkg:
      - awstats
      - geoip-database
      - geoip-database-extra
      - libgeo-ip-perl
      - libgeo-ipfree-perl
      - libnet-dns-perl

- name: /etc/awstats/common.conf
  template:
    src: common.conf.j2
    dest: /etc/awstats/common.conf
    owner: root
    group: root
    mode: 0644
    backup: yes

- name: "/etc/awstats/awstats.{{ item }}.conf"
  template:
    src: "awstats.vhosts.conf.j2"
    dest: "/etc/awstats/awstats.{{ item }}.conf"
    owner: root
    group: root
    mode: 0644
    backup: yes
  loop: "{{ virtual_hosts }}"

# this one is special; we override the one from the loop above
- name: replace vhost for opensourceecology.org
  file:
    path: "/etc/awstats/awstats.www.opensourceecology.org.conf"
    state: absent

- name: /etc/awstats/awstats.opensourceecology.org.conf
  template:
    src: awstats.opensourceecology.org.conf.j2
    dest: /etc/awstats/awstats.opensourceecology.org.conf
    owner: root
    group: root
    mode: 0644
    backup: yes

# this fixes a bug in Debian where the logrotate rule never actually triggers
# awstats to run using `run-parts` because [a] the script is in a dir and
# run-parts won't look inside dirs recursively and [b] the script has a dot in
# its name so run-parts ignores it
#  * https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=890414
- name: enabe module = headers
  file:
    src: /etc/logrotate.d/httpd-prerotate/awstats/prerotate.sh
    dest: /etc/logrotate.d/httpd-prerotate/awstats-prerotate
    state: link
