---
- name: install awstats and plugin depends
  apt:
    update_cache: yes
    pkg:
      - awstats
      - geoip-database
#      - geoip-database-extra
      - libgeo-ip-perl
      - libgeo-ipfree-perl
      - libnet-dns-perl

- name: /etc/awstats/common.conf
  template:
    src: common.conf.j2
    dest: /etc/awstats/common.conf
    owner: root
    group: root
    mode: 0644
    backup: yes

- name: "/etc/awstats/awstats.{{ item }}.conf"
  template:
    src: "awstats.vhosts.conf.j2"
    dest: "/etc/awstats/awstats.{{ item }}.conf"
    owner: root
    group: root
    mode: 0644
    backup: yes
  loop: "{{ virtual_hosts }}"

# this one is special; we override the one from the loop above
- name: replace vhost for opensourceecology.org
  file:
    path: "/etc/awstats/awstats.www.opensourceecology.org.conf"
    state: absent

- name: /etc/awstats/awstats.opensourceecology.org.conf
  template:
    src: awstats.opensourceecology.org.conf.j2
    dest: /etc/awstats/awstats.opensourceecology.org.conf
    owner: root
    group: root
    mode: 0644
    backup: yes
