---
- name: install unattended-upgrades
  apt:
    update_cache: yes
    pkg:
      - unattended-upgrades

- name: 20auto-upgrades
  template:
    src: 20auto-upgrades.j2
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: 0744
    backup: yes

- name: 50unattended-upgrades
  template:
    src: 50unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: root
    group: root
    mode: 0744
    backup: yes
