---
- name: install wazuh prereqs
  apt:
    update_cache: yes
    pkg:
      - auditd

- name: wazuh gpg key
  copy:
    src: wazuh.gpg
    dest: /etc/apt/trusted.gpg.d/wazuh.gpg
    owner: root
    group: root
    mode: 0644

- name: wazuh repo
  copy:
    src: wazuh.list
    dest: /etc/apt/sources.list.d/wazuh.list
    owner: root
    group: root
    mode: 0644

- name: install wazuh manager
  apt:
    update_cache: yes
    pkg:
      - wazuh-manager
  notify: enable wazuh-manager

- name: ossec.conf
  template:
    src: ossec.conf.j2
    dest: /var/ossec/etc/ossec.conf
    owner: root
    group: wazuh
    mode: 0660
    backup: yes
  notify: restart wazuh-manager

- name: local_rules.xml
  template:
    src: local_rules.xml.j2
    dest: /var/ossec/etc/rules/local_rules.xml
    owner: wazuh
    group: wazuh
    mode: 0660
    backup: yes
  notify: restart wazuh-manager

- name: email encryption .forward file
  copy:
    src: .forward
    dest: /var/ossec/.forward
    owner: root
    group: root
    mode: 0644

- name: email encryption script
  template:
    src: sent_encrypted_alarm.sh.j2
    dest: /var/ossec/sent_encrypted_alarm.sh
    owner: wazuh
    group: root
    mode: 0755
    backup: yes
